# Code generated by protoc-gen-crystal. DO NOT EDIT.
# source: packed.proto

require "proto"

module Packed
  class Numbers
    include Proto::Message

    property values : Array(Int32) = [] of Int32
    property scores : Array(Float64) = [] of Float64
    property flags : Array(Bool) = [] of Bool
    property ids : Array(UInt32) = [] of UInt32

    def self.decode(io : IO) : self
      msg = new
      reader = Proto::Wire::Reader.new(io)
      while tag = reader.read_tag
        fn, wt = tag
        case fn
        when 1
          if wt == Proto::WireType::LENGTH_DELIMITED
            reader.read_packed_varint { |v| msg.values << v.to_i32! }
          else
            msg.values << reader.read_int32
          end
        when 2
          if wt == Proto::WireType::LENGTH_DELIMITED
            reader.read_packed_double { |v| msg.scores << v }
          else
            msg.scores << reader.read_double
          end
        when 3
          if wt == Proto::WireType::LENGTH_DELIMITED
            reader.read_packed_varint { |v| msg.flags << v != 0_u64 }
          else
            msg.flags << reader.read_bool
          end
        when 4
          if wt == Proto::WireType::LENGTH_DELIMITED
            reader.read_packed_fixed32 { |v| msg.ids << v }
          else
            msg.ids << reader.read_fixed32
          end
        else
          msg.capture_unknown_field(reader, fn, wt)
        end
      end
      msg
    end

    def encode(io : IO) : Nil
      w = Proto::Wire::Writer.new(io)
      w.write_packed(1) do |buf|
        sub = Proto::Wire::Writer.new(buf)
        values.each { |item| sub.write_int32(item) }
      end
      w.write_packed(2) do |buf|
        sub = Proto::Wire::Writer.new(buf)
        scores.each { |item| sub.write_double(item) }
      end
      w.write_packed(3) do |buf|
        sub = Proto::Wire::Writer.new(buf)
        flags.each { |item| sub.write_bool(item) }
      end
      w.write_packed(4) do |buf|
        sub = Proto::Wire::Writer.new(buf)
        ids.each { |item| sub.write_fixed32(item) }
      end
      write_unknown_fields(w)
    end
  end
end
