# Code generated by protoc-gen-crystal. DO NOT EDIT.
# source: simple.proto

require "proto"

module Simple
  enum Status : Int32
    STATUS_UNKNOWN = 0
    STATUS_OK      = 1
    STATUS_ERROR   = 2
  end

  class Person
    include Proto::Message

    property name : String = ""
    property age : Int32 = 0
    property? active : Bool = false
    property status : Simple::Status = Simple::Status.new(0)
    property tags : Array(String) = [] of String
    property address : Simple::Address = Simple::Address.new

    def self.decode(io : IO) : self
      msg = new
      reader = Proto::Wire::Reader.new(io)
      while tag = reader.read_tag
        fn, wt = tag
        case fn
        when 1
          msg.name = reader.read_string
        when 2
          msg.age = reader.read_int32
        when 3
          msg.active = reader.read_bool
        when 4
          _raw = reader.read_int32
          begin
            msg.status = Simple::Status.from_value(_raw)
          rescue ArgumentError
            msg.add_unknown_varint(fn, _raw.to_u64!)
          end
        when 5
          msg.tags << reader.read_string
        when 6
          msg.address = Simple::Address.decode(reader.read_embedded)
        else
          msg.capture_unknown_field(reader, fn, wt)
        end
      end
      msg
    end

    def encode(io : IO) : Nil
      w = Proto::Wire::Writer.new(io)
      w.write_tag(1, Proto::WireType::LENGTH_DELIMITED)
      w.write_string(name)
      w.write_tag(2, Proto::WireType::VARINT)
      w.write_int32(age)
      w.write_tag(3, Proto::WireType::VARINT)
      w.write_bool(active?)
      w.write_tag(4, Proto::WireType::VARINT)
      w.write_int32(status.value)
      tags.each do |item|
        w.write_tag(5, Proto::WireType::LENGTH_DELIMITED)
        w.write_string(item)
      end
      w.write_embedded(6) { |sub| address.encode(sub) }
      write_unknown_fields(w)
    end
  end

  class Address
    include Proto::Message

    property street : String = ""
    property city : String = ""

    def self.decode(io : IO) : self
      msg = new
      reader = Proto::Wire::Reader.new(io)
      while tag = reader.read_tag
        fn, wt = tag
        case fn
        when 1
          msg.street = reader.read_string
        when 2
          msg.city = reader.read_string
        else
          msg.capture_unknown_field(reader, fn, wt)
        end
      end
      msg
    end

    def encode(io : IO) : Nil
      w = Proto::Wire::Writer.new(io)
      w.write_tag(1, Proto::WireType::LENGTH_DELIMITED)
      w.write_string(street)
      w.write_tag(2, Proto::WireType::LENGTH_DELIMITED)
      w.write_string(city)
      write_unknown_fields(w)
    end
  end
end
